name: CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_posix:
    runs-on: debian-latest
    steps:
    - uses: actions/checkout@v6

    - name: project_configure
      run: cmake ${{github.workspace}} -B ${{github.workspace}}/build

    - name: project_build
      run: cmake --build ${{github.workspace}}/build

  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6

    - name: project_configure
      run: cmake ${{github.workspace}} -B ${{github.workspace}}/build

    - name: project_build
      run: cmake --build ${{github.workspace}}/build

